In [17]:
import sys
import os

PROJECT_ROOT = os.path.abspath("..")
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

import pandas as pd
from src.validation import validate_dataset
from src.logger import setup_logger

In [18]:
logger = setup_logger()

In [19]:
df = pd.read_csv(
    "../data/raw/train.csv",
    dtype={"StateHoliday": "category"},
    low_memory=False
)

df["Date"] = pd.to_datetime(df["Date"])

In [20]:
validate_dataset(df)

2026-03-03 14:09:35,486 - INFO - Starting dataset validation...
2026-03-03 14:09:35,519 - INFO - Dataset validation passed successfully.

In [21]:
df.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  datetime64[us]
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  category
 8   SchoolHoliday  1017209 non-null  int64
dtypes: category(1), datetime64[us](1), int64(7)
memory usage: 63.1 MB

In [23]:
df.describe()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,SchoolHoliday
count,1.017209e+06,1.017209e+06,1017209,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06
mean,5.584297e+02,3.998341e+00,2014-04-11 01:30:42.846062,5.773819e+03,6.331459e+02,8.301067e-01,3.815145e-01,1.786467e-01
min,1.000000e+00,1.000000e+00,2013-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.800000e+02,2.000000e+00,2013-08-17 00:00:00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00
50%,5.580000e+02,4.000000e+00,2014-04-02 00:00:00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00
75%,8.380000e+02,6.000000e+00,2014-12-12 00:00:00,7.856000e+03,8.370000e+02,1.000000e+00,1.000000e+00,0.000000e+00
max,1.115000e+03,7.000000e+00,2015-07-31 00:00:00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00
std,3.219087e+02,1.997391e+00,NaN,3.849926e+03,4.644117e+02,3.755392e-01,4.857586e-01,3.830564e-01

In [24]:
df.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [25]:
df.duplicated(subset=["Store", "Date"]).sum()

np.int64(0)

In [26]:
df["Date"] = pd.to_datetime(df["Date"])
df["Date"].min(), df["Date"].max()

(Timestamp('2013-01-01 00:00:00'), Timestamp('2015-07-31 00:00:00'))

In [27]:
df[df["Open"] == 0]["Sales"].unique()

array([0])

In [28]:
df.sort_values(["Store", "Date"]).head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
1016095,1,2,2013-01-01,0,0,0,0,a,1
1014980,1,3,2013-01-02,5530,668,1,0,0,1
1013865,1,4,2013-01-03,4327,578,1,0,0,1
1012750,1,5,2013-01-04,4486,619,1,0,0,1
1011635,1,6,2013-01-05,4997,635,1,0,0,1

In [29]:
df["Date"] = pd.to_datetime(df["Date"])
df.dtypes

Store                     int64
DayOfWeek                 int64
Date             datetime64[us]
Sales                     int64
Customers                 int64
Open                      int64
Promo                     int64
StateHoliday           category
SchoolHoliday             int64
dtype: object

In [30]:
for col in df.columns:
    print(repr(col))

'Store'
'DayOfWeek'
'Date'
'Sales'
'Customers'
'Open'
'Promo'
'StateHoliday'
'SchoolHoliday'

In [31]:
print("Antes da validação")
validate_dataset(df)
print("Depois da validação")

2026-03-03 14:09:35,852 - INFO - Starting dataset validation...
2026-03-03 14:09:35,875 - INFO - Dataset validation passed successfully.

Antes da validação
Depois da validação

In [32]:
from src.logger import setup_logger
logger = setup_logger()

In [33]:
validate_dataset(df)

2026-03-03 14:09:35,889 - INFO - Starting dataset validation...
2026-03-03 14:09:35,910 - INFO - Dataset validation passed successfully.